### ISSUE TITLE
@cycle/time 0.9.1 Cannot find module './src/mock-time-source' from 'rxjs.js'

### ISSUE THREAD

**Issue by evenchange4** [cyclejs/cyclejs#672]
**Code to reproduce the issue:**

There is a problem of module resolution when I update from `^0.8.0` to `^0.9.1`:

```js 
// error
import { mockTimeSource } from '@cycle/time/rxjs';
```

```
 ● Test suite failed to run
   Cannot find module './src/mock-time-source' from 'rxjs.js'
     at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:179:17)
     at Object.<anonymous> (../../node_modules/@cycle/time/rxjs.js:7:26)
```

**Workaround**

Should I use the `rxjs.js ` file with specific path?

```js
// work!
import { mockTimeSource } from '@cycle/time/lib/rxjs';
```

**Comment by Widdershin** [comment]
Hi @evenchange4, does this work correctly with `^0.9.2`?

**Comment by Widdershin** [comment]
Hi @evenchange4 

Thanks for the issue!

This is an unintended consequence of the way the monorepo compiles packages. All code is outputted directly to the lib directory.

Previously I ran an additional compile step to ensure that `rxjs.js` and `most.js` were present in the root of the compiled package.

I would recommend your workaround in the meantime, and I'll chat to @staltz and @jvanbruegge to see if there's a way we can set this up so you can continue to import as before.

**Comment by IssuehuntBot** [comment]
@issuehuntfest has funded $40.00 to this issue. [See it on IssueHunt](https://issuehunt.io/repos/26316966/issues/672)

**Comment by shriram-svg** [comment]
Opened https://github.com/cyclejs/cyclejs/pull/1003 to restore the generated root `rxjs`/`most` entrypoints and include them in the published package.
