### ISSUE TITLE
Update TypeScript to v2.4

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#640]
I see this error when building with v2.4.1, it works fine with 2.3.4
```
TypeScript error: node_modules/@cycle/dom/lib/MainDOMSource.d.ts(6,22): Error TS2420: Class 'MainDOMSource' incorrectly implements interface 'DOMSource'. 
Types of property 'select' are incompatible.
Type '(selector: string) => DOMSource' is not assignable to type '<S extends DOMSource>(selector: string) => S'.
Type 'DOMSource' is not assignable to type 'S'.
```

**Comment by oriSomething** [comment]
There are some changes the way interfaces works in TS ≥ 2.4.
Probably means that [this line](https://github.com/cyclejs/cyclejs/blob/master/dom/src/DOMSource.ts#L8) needs to be updated

**Comment by staltz** [comment]
TypeScript v2.4 is a breaking change, so I'll rename this issue as an enhancement, it's not Cycle's fault that compilation fails.

**Comment by whitecolor** [comment]
Will @ntilwalli  `skipLibCheck` compiler option help?

**Comment by ntilwalli** [comment]
@whitecolor Thanks.  I'm back on 2.3.4 but I'll try that out when I get a chance.
